//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericApp.Infra.CC.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenericApp.Infra.CC.Localization.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied!.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already registered!.
        /// </summary>
        public static string AlreadyRegistered {
            get {
                return ResourceManager.GetString("AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while establishing a connection to the database server..
        /// </summary>
        public static string CannotConnectToDatabase {
            get {
                return ResourceManager.GetString("CannotConnectToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete referenced record..
        /// </summary>
        public static string CannotDeleteReferencedRecord {
            get {
                return ResourceManager.GetString("CannotDeleteReferencedRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert duplicated row..
        /// </summary>
        public static string CannotInsertDuplicatedRow {
            get {
                return ResourceManager.GetString("CannotInsertDuplicatedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dto to be mapped is null..
        /// </summary>
        public static string CannotMapNullDto {
            get {
                return ResourceManager.GetString("CannotMapNullDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deliver the e-mail..
        /// </summary>
        public static string CouldNotDeliverTheEmail {
            get {
                return ResourceManager.GetString("CouldNotDeliverTheEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find an implementation for the interface {0}..
        /// </summary>
        public static string CouldNotFindAnImplementationForTheInterface {
            get {
                return ResourceManager.GetString("CouldNotFindAnImplementationForTheInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t connect to azure server..
        /// </summary>
        public static string CouldntConnectToAzureServer {
            get {
                return ResourceManager.GetString("CouldntConnectToAzureServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while establishing a connection to the database server..
        /// </summary>
        public static string DatabaseServerUnreacheble {
            get {
                return ResourceManager.GetString("DatabaseServerUnreacheble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input for {0} not found..
        /// </summary>
        public static string DataInputNotFound {
            get {
                return ResourceManager.GetString("DataInputNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted record..
        /// </summary>
        public static string DeletedRecord {
            get {
                return ResourceManager.GetString("DeletedRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired password..
        /// </summary>
        public static string ExpiredPassword {
            get {
                return ResourceManager.GetString("ExpiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate embed token..
        /// </summary>
        public static string FailedToGenerateEmbed {
            get {
                return ResourceManager.GetString("FailedToGenerateEmbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} must be informed..
        /// </summary>
        public static string FieldMustBeInformed {
            get {
                return ResourceManager.GetString("FieldMustBeInformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not allowed. Please use the following: {0}..
        /// </summary>
        public static string FileNotAllowed {
            get {
                return ResourceManager.GetString("FileNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} inactive..
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date argument..
        /// </summary>
        public static string InvalidDateArgument {
            get {
                return ResourceManager.GetString("InvalidDateArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} invalid..
        /// </summary>
        public static string InvalidField {
            get {
                return ResourceManager.GetString("InvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token!.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user or password..
        /// </summary>
        public static string InvalidUserOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not possible to add Role Level Security without existing report..
        /// </summary>
        public static string IsNotPossibleToAddRLSWithoutExistingReport {
            get {
                return ResourceManager.GetString("IsNotPossibleToAddRLSWithoutExistingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid e-mail address..
        /// </summary>
        public static string MustBeValidMailAddress {
            get {
                return ResourceManager.GetString("MustBeValidMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail has been sent by VOLVO. Please do not reply.&lt;br /&gt;&lt;br /&gt;Your new password is: &lt;b&gt;{0}&lt;/b&gt;.
        /// </summary>
        public static string NewPasswordMail {
            get {
                return ResourceManager.GetString("NewPasswordMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password for Volvo Labi System.
        /// </summary>
        public static string NewPasswordSubject {
            get {
                return ResourceManager.GetString("NewPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reports were found in the workspace..
        /// </summary>
        public static string NoReportsInWorkspace {
            get {
                return ResourceManager.GetString("NoReportsInWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No report with the given ID was found in the workspace. Make sure ReportId is valid..
        /// </summary>
        public static string NoReportWithGivenIdInWorkspace {
            get {
                return ResourceManager.GetString("NoReportWithGivenIdInWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doesn&apos;t have a valid vigent period..
        /// </summary>
        public static string NotAValidVigentPeriod {
            get {
                return ResourceManager.GetString("NotAValidVigentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not created..
        /// </summary>
        public static string NotCreated {
            get {
                return ResourceManager.GetString("NotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not deleted..
        /// </summary>
        public static string NotDeleted {
            get {
                return ResourceManager.GetString("NotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not found..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not updated..
        /// </summary>
        public static string NotUpdated {
            get {
                return ResourceManager.GetString("NotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ojbect must not be null..
        /// </summary>
        public static string ObjectMustNotBeNull {
            get {
                return ResourceManager.GetString("ObjectMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object to be removed does not exists..
        /// </summary>
        public static string ObjectToBeRemovedDoesNotExists {
            get {
                return ResourceManager.GetString("ObjectToBeRemovedDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object to be updated does not exists..
        /// </summary>
        public static string ObjectToBeUpdatedDoesNotExists {
            get {
                return ResourceManager.GetString("ObjectToBeUpdatedDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have between 6 and 10 characters..
        /// </summary>
        public static string PasswordMustBeBetween6And10 {
            get {
                return ResourceManager.GetString("PasswordMustBeBetween6And10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain letters and numbers..
        /// </summary>
        public static string PasswordMustContainLettersAndNumbers {
            get {
                return ResourceManager.GetString("PasswordMustContainLettersAndNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully reseted..
        /// </summary>
        public static string PasswordReseted {
            get {
                return ResourceManager.GetString("PasswordReseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully updated..
        /// </summary>
        public static string PasswordUpdated {
            get {
                return ResourceManager.GetString("PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture with size of {0} bytes. Maximum size allowed is {1} bytes!.
        /// </summary>
        public static string PictureWithSizeAboveMaximum {
            get {
                return ResourceManager.GetString("PictureWithSizeAboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record created..
        /// </summary>
        public static string RecordCreated {
            get {
                return ResourceManager.GetString("RecordCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found..
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request could not be processed..
        /// </summary>
        public static string RequestCouldNotBeProcessed {
            get {
                return ResourceManager.GetString("RequestCouldNotBeProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response code not identified..
        /// </summary>
        public static string ResponseCodeNotIdentified {
            get {
                return ResourceManager.GetString("ResponseCodeNotIdentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully generated token..
        /// </summary>
        public static string SuccessfullyGeneratedToken {
            get {
                return ResourceManager.GetString("SuccessfullyGeneratedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} not equal to informed {1}!.
        /// </summary>
        public static string TheFieldIsNotEqualTo {
            get {
                return ResourceManager.GetString("TheFieldIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is another record with same values..
        /// </summary>
        public static string ThereIsAnotherRecordWithSameValues {
            get {
                return ResourceManager.GetString("ThereIsAnotherRecordWithSameValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already one {0} registered with this {1}!.
        /// </summary>
        public static string ThereIsARecordWithThis {
            get {
                return ResourceManager.GetString("ThereIsARecordWithThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type must be serializable..
        /// </summary>
        public static string TypeMustBeSerializable {
            get {
                return ResourceManager.GetString("TypeMustBeSerializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access..
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected error, please try again..
        /// </summary>
        public static string UnexpectedErrorTryAgain {
            get {
                return ResourceManager.GetString("UnexpectedErrorTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected failure occurred.&lt;br&gt;Contact system administration..
        /// </summary>
        public static string UnexpectedFailureOccurred {
            get {
                return ResourceManager.GetString("UnexpectedFailureOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated record..
        /// </summary>
        public static string UpdatedRecord {
            get {
                return ResourceManager.GetString("UpdatedRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not registered. Please contact the system administration..
        /// </summary>
        public static string UserNotRegistered {
            get {
                return ResourceManager.GetString("UserNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for {0} must be between {1} and {2}..
        /// </summary>
        public static string ValueMustBeBetween {
            get {
                return ResourceManager.GetString("ValueMustBeBetween", resourceCulture);
            }
        }
    }
}
